ink-engine-runtime/VariablesState.cs

Just implemented the IEnumerable to iterate throw the keys of the _globalVariables

Make VariablesState inumerable

---

Documentation/WritingWithInk.md

Working through the examples while experimenting with a Java implementation and fell across these minor typos.  What has once been seen cannot be unseen.

Really minor typos

---

ink-engine-runtime/StoryState.cs

There was an example using it in RunningYourInk.md, and it seems useful.

Made VisitCountAtPathString public.

---

Documentation/WritingWithInk.md

Fix typo in WritingWithInk.md

---

Documentation/WritingWithInk.md

Apologies if this pull request isn't just so - still getting the hang of them.

Updated WritingWithInk.md for clarity/grammar.

---

ink-engine-runtime/NativeFunctionCall.cs

Looks like some code got copy-pasted?

AddFloatUnaryOp should take UnaryOp<float>

---

inklecate/InkParser/InkParser_Choices.cs

most minimal fix for the tag crash bug #212

---

Documentation/ArchitectureAndDevOverview.md
ink-engine-runtime/StoryState.cs

outdated comments can be confusing.

Updating comments: Runtime.Text -> Runtime.StringValue

---

Documentation/WritingWithInk.md

Fixed bug in a code sample, fixed a typo in another, and removed unnecessary function calls in a third.

Update to WritingWithInk.md Example Scripts

---

Documentation/WritingWithInk.md

Some very minor text corrections I made while reading through the "Writing With Ink" documentation.

minor text corrections

---

ink-engine-runtime/Story.cs

never too late to fix a typo :-)

fix: s/verison/version

---

Documentation/RunningYourInk.md

Fix typo in documentation

---

ink-engine-runtime/SimpleJson.cs

SimpleJson in the runtime doesn't properly handle string escapes, leading it to output malformed JSON and deserialize valid JSON incorrectly. This can be seen even in the TheIntercept.ink example, where the source file has tab characters. The tab characters were being output as unescaped in strings, meaning compliant JSON readers reported errors in ink.json files.
This PR changes SimpleJson to correctly escape string characters per the JSON specs, as well as properly read all valid JSON escape sequences when reading. Control characters such as \r continue to be ignored for both reading and writing.

always write valid json and read more valid json

---

compiler/InkParser/InkParser_CharacterRanges.cs

I request that the Korean identifier be officially supported. #566

support for Korean identifier

---

ink-engine-runtime/SimpleJson.cs

An error on line 56 of InkParser_Sequences.cs resulted in incorrect conditional behavior. This has been fixed by removing the curly braces entirely.

Fixing curly brace inclusion error

---

README.md

Fixed link to ink-unity-integration package in README.md

---

Documentation/WritingWithInk.md
compiler/InkParser/InkParser_CharacterRanges.cs

adding latin1Supplement letters

Update InkParser_CharacterRanges.cs for adding latin1extended letters to the identifiers.

---

ink-engine-runtime/NativeFunctionCall.cs

Fix for broken divert not-equals operator

---

Documentation/WritingWithInk.md

🤔 do you mean "Fallback"  choices can be sticky too ?

"Fallback" choices can be sticky too

---

Documentation/WritingWithInk.md

Sounds like there are some new requests to add in a table of contents to `WritingWithInk.md` on the Discord server. I'm resubmitting this change which I've found very useful, but unobtrusive.

Add Table of Contents to WritingWithInk.md

---

Documentation/WritingWithInk.md

Fixes several broken anchor links in WritingWithInk.md

fix broken anchor links

---

inklecate/CommandLineTool.cs

Make inklecate stop outputting BOM when compiling to JSON

---

inklecate/CommandLineTool.cs

I was playing around with the CLI and noticed this small typo in the help output

Small typo for inklecate

---

Documentation/ArchitectureAndDevOverview.md

Revert "Typo in ArchitectureAndDevOverview.md"

---

ink-engine-runtime/JsonSerialisation.cs

https://github.com/inkle/ink/issues/857

Fixed an issue #857: Choice tags are gone after state reloading 
