inkle/ink

Documentation/WritingWithInk.md

in "Advanced: all options can be labelled"

Fix "thrown" typo

---

Documentation/WritingWithInk.md

This seems like it is a typo, if my understanding of the function syntax is correct.

Fixes typo in the first tunnels example

---

Documentation/WritingWithInk.md

Was confused by this, since the examples are inconsistent, but based on my tests, this seems to be correct.
- A string expression cannot contain a divert, so the first example should not have quotation marks.
- Also, I assume the example is supposed to use the divert VAR defined in it.

Fixing some errors in the examples

---

.travis.yml
README.md

Hi!
This pull request adds support for the [Travis-CI](https://travis-ci.org) continuous integration service. If you go onto Travis and enable this repo (it's free for OSS projects), it'll automatically build the app and run the tests every time a new commit hits master. You can also set up a GitHub integration to automatically run a CI build against any incoming pull requests, and warns you if it would cause the build to break. (These are both things you'll have to do as the repo owner, but they should take < 5 min. Happy to walk you through them, but they're incredibly straight-forward.). This also adds a nice little badge to the README showing the current build status. I've tested this on my own fork, including adding/removing a failing test case to make sure that Travis failed/passed …

Add support for Travis-CI

---

tests/Tests.cs

I ran into an issue with failing tests, which turned out to be Git on Windows autoconverting some line endings in a way that broke literal string comparisons.
There might be other ways to address this (like a .gitattributes file) but adding a warning comment was simple and won't result in complications somewhere else.

Tests.cs line termination warning for Windows users.

---

.gitattributes
tests/Tests.cs

This has the changes I talked about in https://github.com/inkle/ink/issues/45 . Basically this should guard against accidentally CRLFing Tests.cs, and over time will bring other files into consistent LF format (currently the source tree mixed LF and CRLF). See longer discussion in the issue.

Add .gitattributes, remove Tests.cs comment.

---

inklecate/StressTestContentGenerator.cs

The stress test generator is helpful for speed testing various file
formats, and previously it did not work at all. My changes were mostly of
the stab-in-the-dark variety, but at least the stress test runs without
complaint now.

Fix stress test generator

---

ink-engine-runtime/Divert.cs

targetContent caches the result of resolving _targetPath, but the cache never invalidates, so targetContent, and in some cases, targetPath, can be stale. This change invalidates the cache when _targetPath changes.

Invalidate cache of targetContent

---

Documentation/WritingWithInk.md

'Includes and Stitches' - subtitle 'Scripts can combined' changed to 'Scripts can be combined'

modest typo fix in 'Includes and Stitches' section

---

inklecate/CommandLineTool.cs

After trying the new *Inky* editor on Windows (it's awesome, despite some quirks!) I've noticed that the player view won't show German umlauts (or any other UTF-8 characters) properly:
After poking around a bit, I've noticed that it seems like *Inklecate* never sets any encoding, while *Inky* expects the console input/output to be UTF-8.
After setting the encoding, *Inky* properly shows umlauts and they're still properly shown in console sessions as well (Windows 10).
The change is minimal, but I figured writing a PR would be the same work as creating an issue. Feel free to close this and implement it somewhere else, if you want to.

Set UTF-8 encoding for Inklecate

---

ink-engine-runtime/CallStack.cs

Clone Element's temporary variables dictionary instead of referencing the same dictionary (leading to variable errors in threads)

Clone Element's temporaryVariables

---

ink-engine-runtime/Story.cs

The previous test :
if (value.GetType () == typeof(T))
return (T) value;
didn't work if "value" type inherited from T
That meant if an external function was supposed to accept any 'object' and was fed with a 'string' it refused it with the error 'Failed to cast String To Object'

Fix casting issue in TryCoerce function

---

ink-engine-runtime/SimpleJson.cs
ink-engine-runtime/Value.cs
inklecate/ParsedHierarchy/Number.cs
tests/Tests.cs

Should now consistently use '.' as the separator, no matter the system.

Fixed float parsing/serialization for systems that use ','

---

inklecate/ParsedHierarchy/DivertTarget.cs

```
{-> somewhere == 5}
=== somewhere ===
a -> DONE
```
caused an exception at runtime and it all to crash.
```
{5 == -> somewhere}
=== somewhere ===
a -> DONE
```
gets rejected like it should be.
The reason was a copypaste error, which is fixed in this PR - now the first case also gets rejected by the compiler.

fixed copypaste error resulting in lacking checks

---

ink-engine-nuget/Inkle.Ink.Engine/Properties/AssemblyInfo.cs
ink-engine-nuget/Inkle.Ink.Engine/project.json
ink-engine-runtime/Story.cs
ink-engine-runtime/StoryState.cs
ink-engine-runtime/ink-engine-runtime.csproj

This makes the DLL usable by a wider range of consumers. I'm using
profile 259 as that seems to have the broadest compatibility (see
http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/)
With this change, the NuGet package should work out of the box on
new installations of Xamarin, as well as VS 2013 and later.
It should not affect Unity users as they're including the source
directly.

Convert ink-engine-runtime.csproj to a PCL (Portable Class Library)

---

LICENSE.txt
README.md

Per Github recommendation, move the license into its own file.
If accepted, the README will link to the license file.
Accepting this pull request will update the copyright year and have Github officially identify this project as MIT-licensed.

Move License Text To Own File

---

ink-engine-runtime/StoryState.cs

Not sure how this has not been an issue before, but it's recently started causing errors in our external function calls - perhaps they just hit a certain level of complexity? The issue seen in the inkjs prototype is that _originalCallstack is null by the time the external function finishes, when it then attempts to put that state back in again. The solution here fixes the issue in inkjs but I've not repo'd the issue in "real" ink.

Need to copy storyState._originalCallstack

---

Sublime3Syntax/ink.YAML-tmLanguage
Sublime3Syntax/ink.tmLanguage

- Added support for `INCLUDE` and `EXTERNAL` like `VAR` and `CONST` are already supported.
- Fixed stitch declarations having wrong captures copied directly from knot declarations (even though knots can be functions while stitches can't, causing stitch names to be scoped as `keyword.function`.

More tmLanguage fixes

---

Sublime3Syntax/ink.YAML-tmLanguage
Sublime3Syntax/ink.tmLanguage

The Ink engine supports choices that look like this :
```
* [ \[bracketted\] ]
```
The .tmLanguage file didn't support that and stopped at the first `]`
I just edited the two files, and didn't proceed to the whole process described in the readme since I don't use ST or mac.
I tested it in vscode though and it works. Shouldn't break anything either.

Support for escaped square-brackets in choice-only content.

---

build_release.command

When I run:
```
$ bash build_release.command
```
mkbundle seems to not search` inklecate/bin/Release` on my machine which leads to the following error message:
```
ERROR: Unable to load assembly `ink_compiler' referenced by `/Users/blah/inklecate/bin/Release/inklecate.exe'
```
Despite `ink_compiler.dll` sitting right next to `inklecate.exe` in `inklecate/bin/Release`. This can be fixed by explicitly adding `inklecate/bin/Release` to the search path using -L.
I guess this works normally so I'm not sure why this is the case for me but I thought I would upload a patch anyway in case it is helpful for others :)

Explicitly set search path for mkbundle in build_release.command

---

Documentation/ink_JSON_runtime_format.md

This opcode is misdocumented; it does not (or no longer) pop from the evaluation stack.

`value` does not actually accept parameters.

---

Documentation/ArchitectureAndDevOverview.md
Sublime3Syntax/README.md

They were causing GitHub markdown rendering to look wrong for a couple of headings:
Before:
After:

Replace non-breaking spaces with normal spaces in md files

---

ink-engine-runtime/Story.cs

When passing in only a specific variable name with the observer set to null, function will clear all observers for the given variable.

Made observer param in RemoveVariableObserver optional

---

ink-engine-runtime/Story.cs

Fixing Issue 533 - https://github.com/inkle/ink/issues/533
When removing variableObservers, the dictionary holding them may still hold a key with `null` as a value. This will cause an Exception to be thrown if that variable is changed again. This fix ensures empty keys are completely removed from that dictionary.

Ensure keys are removed from _variableObservers if they are empty.

---

Documentation/WritingWithInk.md

This is a very minor fix. Knots aren't introduced until subsection 3) Knots.

Documentation: Remove knot from Tags section

---

Documentation/WritingWithInk.md

Fixes #485 
The hallway example in the threads documentation contains an error (the thread requires a param but the call to the thread does not provide it - and one of the conditions within the thread does not use the param).

Fix threads documentation error

---

Documentation/ink_JSON_runtime_format.md

Noticed a small typo in the runtime docs, looks like unary negation got renamed in ee008e51 to make room for set inversion.

Small typo for JSON runtime format docs: "~" -> "_".

---

README.md

Right now, if you run inklecate on Ubuntu according to the instructions in the readme, you'll get an unhelpful exception due to a missing dependency. 
`
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in 
<22aa2ecb8c6b41f494a352131f83f312>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or 
assembly or one of its dependencies.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in 
<22aa2ecb8c6b41f494a352131f83f312>:0`
The …

Documentation: Update the README with correct dependencies for Linux.

---

compiler/InkParser/InkParser.cs
compiler/StringParser/StringParser.cs
compiler/StringParser/StringParserState.cs
ink-engine-runtime/DebugMetadata.cs

Title says all. I'm not too sure about the wording: `characterInLineIndex` sounds a bit weird, but `characterIndex` was already taken.
Sorry about the noise, the editor removed trailing whitespaces and converted tabs to spaces in `InkParser.cs`. (I can revert those changes, but I think Joe mentioned they're okay on another PR.)
Thanks for having a look!

Keep track of character indices in DebugMetadata (LSP 1/2)

---

compiler/Compiler.cs
inklecate/CommandLinePlayer.cs

In the past it was possible to interpret .json files with inklecate (skipping the .ink -> .json compilation step).
This restores support for that feature by moving the basic input handling off Compiler and back onto CommandLinePlayer. 
The more advanced features (getting debug info and evaluating Ink) stay on Compiler and are only available when starting with .ink file. This resolves #641
Cheers!

Support playing .json files with inklecate

---

Documentation/WritingWithInk.md

If you used that example as written, Inky would give a warning to use "* ->" syntax for a fallback choice. Rewritten to not give an error.

update for wack_a_mole example

---

Documentation/RunningYourInk.md
ink-engine-runtime/Story.cs
ink-engine-runtime/StoryState.cs

Added those functions to Story:
- `story.aliveFlowNames` - the names of currently alive flows. A flow is alive if it's previously been switched to and hasn't been destroyed. Does not include default flow.
- `story.currentFlowIsDefaultFlow` - true if the default flow is currently active. By definition, will also return true if not using flow functionality.
- `story.currentFlowName` — a string containing the name of the currently active flow. May contain internal identifier for default flow, so use `currentFlowIsDefaultFlow` to check first.

Added some parallel flow utility functions

---

compiler/Compiler.cs
compiler/Plugins/Plugin.cs
compiler/Plugins/PluginManager.cs
inklecate/CommandLineTool.cs

Here we go! The ink compiler has plugin support now! Pass `-x directory` on the command line, and inklecate will import all the .dlls it finds in that folder (as long as those .dlls contain classes which implement the interface `Ink.IPlugin`).
The only significant change I've made here (beyond finishing the unfinished code) was the addition of a PreParse method in the `IPlugin` interface, which accepts and returns a string. A preprocessor, if you will.

Plugin support for the compiler!

---

Documentation/WritingWithInk.md

Fixing broken link to #multiline-blocks and removing ' and " from links to be consistent with the rest of the document.

Fixing links

---

.travis.yml
InkTestBed/InkTestBed.csproj
README.md
build_for_inky.command
build_release.command
ink-engine-runtime/ink-engine-runtime.csproj
ink.sln
inklecate/inklecate.csproj
profiler.command
tests/tests.csproj

.NET 6.0 is the latest LTS release of .NET, and .NET Core 3.1 will reach [the end of support](https://devblogs.microsoft.com/dotnet/net-core-3-1-will-reach-end-of-support-on-december-13-2022/) this October.
* The method of bundling everything in a single-file executable has changed between 3.1 and 6.0, in particular Windows executable is not a single file anymore
* Trimming of assemblies during single-file bundling is much more complicated and not recommended anymore, so I have disabled this feature (this means slightly increased file size of releases)
* Inclecate usage instructions in README.md should probably be changed, as it was using native Linux binary since migration to .net core 3.1

Upgrade target framework and scripts from .net core 3.1 to .net 6.0

---

ink-engine-runtime/VariablesState.cs

Fixed an issue when using story.ResetState() _defaultGlobalVariables is null and throws.

Check is null _defaultGlobalVariables on WriteJson

---

build_for_inky.command
build_release.command
compiler/ink_compiler.csproj
ink-engine-runtime/ink-engine-runtime.csproj

Revert the change made in 5d92a5b3ba3c7a040892ff67649a58c4928adbc6. There's no reason to target net6, and doing so breaks compatibility with systems still targeting older frameworks.
I'm torn about whether we should retarget the compiler as well. It might be a good thing now that I think about it? Happy to hear your opinion about it.

Retarget the runtime to netstandard

---

README.md

Fix for #791 . Updating the README with current (no mono dependency) launch instructions.

Update README with current Linux launch instructions.

---

ink-engine-runtime/StoryState.cs

Swap DateTime.Now to DateTime.UtcNow so to avoid an OSX Desktop Permissions request on build.
This commit has been pushed to the Unity repo already.

Swap DateTime.Now to DateTime.UtcNow

---

inklecate/CommandLineTool.cs

Fixed an issue that was causing Inklecate to fail when executed as a process from Unreal editor.
The console created by UE does not allow the encoding to be changed.

Inklecate Unreal Editor 5 fix

---

ink-engine-runtime/InkList.cs
tests/Tests.cs

I've been slowly working on a Swift port of the ink runtime and came across a bit of code that didn't seem quite right. This pull request fixes the line and adds a test to verify it.

Fix checking for upper bound's type in LIST_RANGE

---

Documentation/WritingWithInk.md

The example was resulting in an error: Expected an "-else:" clause here...

WritingWithInk: fix a Global Constants example

---

ink-engine-runtime/CallStack.cs

Fix for: https://github.com/inkle/ink/issues/787

Fix for approximate-location warning when loading a saved state, which could crash with a null pointer.

---

compiler/InkParser/InkParser_CharacterRanges.cs

Enables characters for languages of the Chinese and is a subset of the official * Chinese* unicode range `\u4E00`-`\u9FFF`.

support for Chinese identifier

---

ink-engine-runtime/SimpleJson.cs

When writing a large amount of JSON to a StreamWriter it's possible for the JSON to get truncated because the writer is never flushed before it's closed. This PR changes SimpleJson to flush whenever the end of an object is written and the state stack becomes empty.
To reproduce the truncation (before this change) you can do:
```c#
using (var stream = File.Open(jsonFilePath), FileMode.Create))
{
story.ToJson(stream);
}
```
On my box my particular ink script results in a truncated JSON file a bit longer than 5,000 chars. After the fix it results in a complete JSON file over 6,000 chars.

Flush the writer when a full object is written

---

compiler/InkParser/InkParser_CharacterRanges.cs

1. Renamed Chinese character range to CJKUnifiedIdeographs. (Matching Unicode plane name)
2. Added Hiragana and Katakana

Add Hiragana and Katakana character ranges

---

Documentation/WritingWithInk.md

Changed "We *feel* into companionable silence" to "We *fell* into companionable silence", which I'm assuming was the original intent.

Fix minor typo in WritingWithInk.md
